### ISSUE TITLE
Scroll & drag-drop does not work together

### ISSUE THREAD

**Issue by be-ndee** [timruffles/mobile-drag-drop#123]
I have an iPad with iOS 11.2.6. I used the polyfill with config `holdToDrag` set to `300`. When I start scrolling on my element, the drag-drop behaviour also starts with a little delay. So the delay seems to work, but scrolling and drag-drop is mixed up and not working correctly.

I used the polyfill as in the explanation and created an `dragenter` listener.

```
import {polyfill} from "mobile-drag-drop";

polyfill({
  holdToDrag: 300
});
```

```
document.addEventListener('dragenter', (event) => {
  event.preventDefault();
});
```

Does anyone have an idea how to fix this? Or have I forgotten some configuration?

**Comment by reppners** [comment]
I'm pretty sure you need the workaround mentioned in https://github.com/timruffles/mobile-drag-drop/issues/77

```JS
window.addEventListener( 'touchmove', function() {})
```

Sorry it's a bit hidden in the README and should be more obvious since theres a big chance this polyfill is used on iOS Safari > 10.

If the workaround works for you please leave the issue open until it's more prominently mentioned in the README :)

**Comment by be-ndee** [comment]
It's not working for me... still starts the drag-behaviour when I scroll.

**Comment by reppners** [comment]
Hmm ok I guess I know where the problem is coming from. It's not the body/document that's scrolling in your case, right? Since scroll events don't bubble it can be pretty hard to detect that the polyfill is supposed to cancel drag start. Touchmove Events are supposed to cancel drag start as well. Do you have any custom touch event handling in place that might interfere with the polyfill?

**Comment by be-ndee** [comment]
Yes, I have some nested divs with fixed-sizes and then there is one div, which is scrollable. But no, I don't have any touch handling.

**Comment by reppners** [comment]
Please check the recent release candidate [2.3.0-rc.1](https://www.npmjs.com/package/mobile-drag-drop). It includes improved logging for debugging issues regarding `holdToDrag` (include the unminified index.js to get console logs) and a fix that will most likely remedy this issue.

**Comment by be-ndee** [comment]
It seems to work with this version 👍

**Comment by reppners** [comment]
Awesome 😀
