### ISSUE TITLE
Unexpected Performance Issue

### ISSUE THREAD

**Issue by walkingriver** [timruffles/mobile-drag-drop#146]
I'm seeing a performance issue I simply cannot explain. When I remove this library, the issue vanishes. The trouble is, I really want this to work on my iPhone. What's weirder is that the performance issue depends on where I begin the drag operation. See the attached animation for reference. If I drag a tile from the bottom div, it's great. If I drag an item from the grid, it is horrible. Any thoughts? I wouldn't have thought simply having 16 separate draggable areas would cause this.
![mobile-drag-drop](https://user-images.githubusercontent.com/1752021/48668337-e021e580-eab8-11e8-82f6-d78929411465.gif)

**Comment by reppners** [comment]
Thanks for reporting. I don't have an explanation yet. Some projects where I used this polyfill had similar views as far as number of draggables and dropzones are concerned.

Any chance you can provide a reproduction, either a git repo I can clone or a stackblitz/plunkr? Did you test on Android, too? Can you provide the version(s) of iOS where its occuring?

**Comment by walkingriver** [comment]
I've opened up the repo. Feel free to have a look. Thanks.
https://github.com/walkingriver/foreword

It happens on Chrome on the Mac and Mobile Safari. I have not yet tried an Android device.

**Comment by walkingriver** [comment]
I just installed it on a Pixel running Pie. Same exact behavior. The iPhone 7 is running iOS 12.1.

**Comment by reppners** [comment]
Thanks, I've found the cause: https://github.com/walkingriver/foreword/blob/d70f56096d696b14cb374f7c9e6bb185bdabc5e8/src/app/home/home.page.scss#L1

The problem is the `transition` on the `.board-tile` class. Since the class is on the draggable element what happens on `dragstart` is that all applied css properties at that specific time are copied onto the clone of the draggable element that is created to serve as drag image. This is done to preserve styling when the clone is added to the DOM at the root element.

I removed the class and did not see any change in the new game animation so this is probably fine.
```scss
.boom {
  transition: 0.5s;
}
``` 

If you need a transition on the draggables you can achieve it by conditionally activating some css class on a parent element so in normal drag and drop operations there would be no transition property active on the tiles. Example
```scss
.animate-new-game {
  .board-tile {
    transition: .5s
  }
}
```

**Comment by walkingriver** [comment]
Wow. I had forgotten all about that css class. It was something I had been goofing off with, and I doubt I'll even use it. Thanks for taking a look and responding so quickly!

**Comment by reppners** [comment]
No problem, you might want to check out my angular drag and drop module (shameless self promotion :laughing:)

https://github.com/reppners/ngx-drag-drop
