### ISSUE TITLE
TypeError in beta release

### ISSUE THREAD

**Issue by ge65cer** [timruffles/mobile-drag-drop#173]
Our exception logging captured a stacktrace which leads back to this library.
https://sentry.ase.in.tum.de/share/issue/6ef45483056040eb9cc96706bea336ef/

Stacktrace snippet:
```
TypeError: Cannot read properties of undefined (reading 'length')
  at St(webpack:/./node_modules/mobile-drag-drop/index.min.js:2:9182)
  at t(webpack:/./node_modules/mobile-drag-drop/index.min.js:2:9097)
  at y(webpack:/./node_modules/mobile-drag-drop/index.min.js:2:9061)
  at dragImageSetup(webpack:/./node_modules/mobile-drag-drop/index.min.js:2:8597)
  at o(webpack:/./node_modules/mobile-drag-drop/index.min.js:2:3877)
  at apply(webpack:/./node_modules/mobile-drag-drop/index.min.js:2:5277)
```

Relevant line: `{snip} HTMLElement&&(i.style.pointerEvents="none"),i.children.length)for(var s=0;s<i.children.length;s++)t(i.children[s]);if(i.shadowRoot&&i.sh {snip}`

Version: 3.0.0-beta.0
Browser: Chrome Mobile 103.0.0
Device: Moto X4, Android 9

**Comment by ge65cer** [comment]
The same devices seem to trigger another type error, maybe related? https://sentry.ase.in.tum.de/share/issue/1971591219e6431d9297466406f38229/

**Comment by reppners** [comment]
Thanks for reporting! Will look into it.

**Comment by johanquiroga** [comment]
I've been facing this issue, and it seems the fix is pretty straightforward.
So I tracked down the issue to this line https://github.com/timruffles/mobile-drag-drop/blob/dad75410543396ff28b7dcf1462574f1b5b46e31/src/internal/dom-utils.ts#L88
The issue for me was that I was hitting a node that didn't have any more children, so it was `undefined`.

just adding a check before accessing the `.length` property fixed this for me, i.e. `node.children && node.children.length`
