### ISSUE TITLE
rename

### ISSUE THREAD

**Issue by timruffles** [timruffles/mobile-drag-drop#30]
this should be renamed to 'mobile-html5-drag-drop', as it supports Android.

**Comment by jmeas** [comment]
:+1:

@timruffles, if you want any help maintaining this lib lemme kno'.

**Comment by timruffles** [comment]
Yup that'd be marvellous.

**Comment by jmeas** [comment]
Add me as a collab? I won't break everything – promise. :P

**Comment by jmeas** [comment]
> An additional edit is required to the patch necessity detection code.

@xstrom, what is the extra patch to make this work on Android?

**Comment by jmeas** [comment]
I had a chance to look into it. The offending line [is here](https://github.com/timruffles/ios-html5-drag-drop-shim/blob/master/ios-drag-drop.js#L16), where it searches only for iOS devices.

I forked the library [here](https://github.com/jmeas/ios-html5-drag-drop-shim), added a Modernizr dep, and made it so that it *should* support all touch devices. 

The patch can be seen [here](https://github.com/jmeas/ios-html5-drag-drop-shim/blob/master/ios-drag-drop.js#L16). It can be installed via bower through:

`bower install https://github.com/jmeas/ios-html5-drag-drop-shim.git#57319bb1df3f072bde`

===

Unfortunately, I don't have the time to redo the build step for this library, so the Modernizr dep requires that you expose Modernizr on `window`, and you'll need to shim it if you're using AMD.

**Comment by rafde** [comment]
Verified @jmeas update worked.

**Comment by xStrom** [comment]
I haven't done any extensive testing, but my own production code has that line set as the following. It works on the few Android devices that have been tested.

```javascript
var needsPatch = !(dragDiv || evts) || /iPad|iPhone|iPod|Android/.test(navigator.userAgent);
```

**Comment by timruffles** [comment]
Hi @jmeas - sorry this fell off my todo list. Collab added - patch away. We've stuck to PRs so far, rather than pushing to master, which has worked well.

**Comment by jmeas** [comment]
> We've stuck to PRs so far, rather than pushing to master, which has worked well.

Of course.

> I haven't done any extensive testing, but my own production code has that line set as the following. It works on the few Android devices that have been tested.

Want to make a PR for this? I'll review, merge, and cut a release.

**Comment by reppners** [comment]
rewrite is available renamed to https://www.npmjs.com/package/drag-drop-polyfill

**Comment by xStrom** [comment]
This issue has been left dangling for some time now, and it's gotten a bit confusing.

Current status:
GitHub: **ios-html5-drag-drop-shim**
NPM: **drag-drop-webkit-mobile** (master) / **drag-drop-polyfill** (2.0)
Bower: **drag-drop-webkit-mobile**

Also @timruffles originally suggested renaming to **mobile-html5-drag-drop**, which we aren't using anywhere as of now.

GitHub seems to support pretty [easy renames](https://help.github.com/articles/renaming-a-repository/) while [redirecting the old name](https://github.com/blog/1508-repository-redirects-are-here).
NPM doesn't seem to support renaming or redirects. However we could create a new package and [deprecate the old packages with a custom message](http://stackoverflow.com/questions/28371669/renaming-a-published-npm-module).
Bower doesn't seem to support renaming or redirects. I'm not even sure if the old bower package will continue working if we create a new one and change our bower.json. We can [delete the old one](https://bower.io/docs/creating-packages/#unregister) though.

I think we should choose one name and work towards using that name everywhere. In addition I think this rename party should happen when we promote the 2.0 branch to master.

Now regarding the names themselves:

**ios-html5-drag-drop-shim** & **drag-drop-webkit-mobile** look flawed as the 2.0 branch supports engines besides webkit.
**drag-drop-polyfill** is nice and short, and it could better signal a mission that we polyfill this based on feature detection and thus it works even on desktop Chrome (in touch mode). It loses the signal that in practice almost all usage is for mobile.
**mobile-html5-drag-drop** has a stronger signal towards the fact that this is mostly used for mobile devices, although our code actually heavily depends on touch (mobile or not) and we don't polyfill support if there's no touch (even on mobile). The **html5** part seems a bit redundant in 2017.

Some other variants in the same style:

**mobile-drag-drop** is short and to the point, even if technically misleading.
**touch-drag-drop** is technically correct, but I'm not sure if being correct is worth the cost in losing the immediate understanding that **mobile** gives.

So, what do you guys think, should we migrate to a single name when 2.0 is ready? Which name?

**Comment by timruffles** [comment]
Great research and analysis!

I think a single name is the right way. mobile-drag-drop is a good concise
package name, and we could still mention 'polyfill' in the readme etc for
findability.

**Comment by xStrom** [comment]
I think that going with **mobile-drag-drop** is a fine choice.

@reppners thoughts?

**Comment by reppners** [comment]
Great writeup, didn't even remember there was the `drag-drop-webkit-mobile` published.

With the last rename to `drag-drop-polyfill` I intentionally did leave out the `mobile` because of the reason you mentioned (targeting not only mobile devices but any touch device), mostly because at work I maintain compatibility with fixed-mounted touch panels that run Chrome so it seemed appropriate.

Ultimately I'm fine with `mobile-drag-drop` as its also simple and concise and the support range of the polyfill will be easily visible when glancing at the README 👍

**Comment by timruffles** [comment]
Okay - shall we rename this repo?

**Comment by xStrom** [comment]
I still think we should perform the rename (and all related tasks) once the 2.0 branch is ready enough (which is to say, promoted to master). So not yet, but hopefully soon.

**Comment by reppners** [comment]
I think the rewrite branch is ready :rocket: How do we proceed?

**Comment by timruffles** [comment]
Fantastic! Will have a look tonight.

**Comment by timruffles** [comment]
@reppners sorry I'm being a bottleneck here! Looks great, and I'm happy for you to go ahead!

**Comment by reppners** [comment]
@timruffles Thanks for doing the review 👍 

Just published the last prerelease under `drag-drop-polyfill` where only the release files are published on npm for flat imports and the least install overhead. Release files now just need to be committed for bower. I don't know how long we should keep bower support around since they kind of deprecated themselves for future use.

Proposal for the next steps for switching to v2, please chime in if anything wrong
* [ ] rewrite: rename package in package.json/bower.json, set 2.0 as version
* [ ] rewrite: rename files/types/classes/UMD-name to reflect the new package name
* [ ] rewrite: remove 1.x stuff
* [ ] rewrite: update README and CHANGELOG
* [ ] master: branch to `1.x`
* [ ] merge rewrite in master
* [ ] rename repository
* [ ] publish 📦
* [ ] deprecate old packages 📦 🗝  
* * [ ] `drag-drop-webkit-mobile`
* * [ ] `drag-drop-polyfill`
* [ ] close all `fixed in rewrite`-issues
* [ ] have an ice-cooled beverage 🍻

New name will be `mobile-drag-drop`.

**Comment by reppners** [comment]
@timruffles It's done! You're in charge of the repository rename :)

**Comment by timruffles** [comment]
@reppners sorry for dropping the ball on this!

**Comment by timruffles** [comment]
@reppners have done the rename, thanks for all the hard work you did on this! 🙌🎉

Let's make sure to do the ice-cooled 🍻if any of us are at the same conference/city/etc some time :)

**Comment by reppners** [comment]
No worries :) Thx for taking care! Maybe there's a conference in London to attend as an excuse to meet up for a pint or two 😆
